### ISSUE TITLE
Set filter programmatically

### ISSUE THREAD

**Issue by sraedler** [davidegironi/advanceddatagridview#117]
I would like to filter a column by a value, but with the possibility to continue filtering or to display the removed values afterwards via the GUI.

With the "LoadFilterAndSort" it is not possible to adjust the filters afterwards. 

Is there a way to make this possible? I did not find anything in the sample.

Edit: Basically, I want to programmatically set a filter with the same behavior as in the GUI dropdown.

**Comment by davidegironi** [comment]
Hello, take a look here: https://github.com/davidegironi/advanceddatagridview/issues/79

**Comment by sraedler** [comment]
Unfortunately, it is not what I intend to do.

I want to display a table when starting an application. The table contains entries where one column contains a Boolean value. This shows if the record in this row is completed.

When starting the application I want to display only complete records, but give the user the possibility to display all records available (incl. uncompleted ones).

With the CleanFilterAndSort method this would be possible, but then I need an extra button or control to unload the filter, right?

**Comment by davidegironi** [comment]
Due to internal ADGV strcuture it's not possible to set a filter pragmatically. It's something I want to add, but currently I don't have the time to do this.
To achive your goal there's two things that comes in to my mind:
1) you can override the On Filter changed event, to and built some custom code there
2) in my opinion the simpler and claner way to do this is to filter the datasource, putting a filter on "top" of adgv loading. If you look as example at the dentned project (https://github.com/davidegironi/dentned) you can find on many forms a datasource filter (on view is top left).

**Comment by sraedler** [comment]
Thanks for helping!

**Comment by peros550** [comment]
Hi David, did you have time to check this feature? It would be a very nice addition.

**Comment by davidegironi** [comment]
Hello @peros550 , unluckily not yet.

**Comment by peros550** [comment]
no wories, I just followed your advice above and filtered the data one step before I pass them to the Datagridview. Having the option to work with datagridview's UI , in terms of filtering, would be great. All the best.
