### ISSUE TITLE
Treenoad loads very slow when much unique datarow (column "ID")

### ISSUE THREAD

**Issue by Csontikka** [davidegironi/advanceddatagridview#135]
Hello,

I'm experiencing performance issues with the AdvancedDataGridView component, specifically when applying filters to the ad ID column. Here are the details of the issues:

Slow Initial Loading: The first time I attempt to filter by the ad ID column, the tree node loads extremely slowly. This column contains unique identifiers for each row. Here is an image showing the filter button on the column's header: 

![image](https://github.com/davidegironi/advanceddatagridview/assets/10008500/2a773c49-ec7f-4dfc-a797-017a53c892cb)

Error on Expanding Filter Selection: When the filter selection contains more than 10,000 unique entries, a "..." appears at the end of the filter list. Clicking on this results in an error. Here's the error message:

Zuby.ADGV.MenuStrip.CheckList_NodeMouseDoubleClick(Object sender, TreeNodeMouseClickEventArgs e)

Request for Enhancement or Bug Fix:

Is there a way to optimize the filtering process to prevent slow loading times?
Alternatively, could there be an option to disable the filter selection tree node for the "ID" column while keeping other sorting and filtering functionalities intact?

Thank you!

**Comment by davidegironi** [comment]
Hello,

as for the exception, thank you for making me notice. It has been fixed in version 1.2.x.14
For long lists the "..." is added by default to prevent long time loading. On my 2nd gen i7 it takes almost 5 sec to load a 11.000 element list.
If you want you can prevent the checklist filter to be active on a specific column just by calling the SetFilterChecklistEnabled 
 on that specific column. Like in the sample project happens for column "guid" advancedDataGridView_main.SetFilterChecklistEnabled(advancedDataGridView_main.Columns["guid"], false);
Also you can set the max number of show checkbox (default is 10000) using the SetFilterChecklistNodesMax method. Like so for 1000 elements advancedDataGridView_main.SetFilterChecklistNodesMax(1000);
