### ISSUE TITLE
Filters columns stay blocked

### ISSUE THREAD

**Issue by pereiragtiago** [davidegironi/advanceddatagridview#147]
when i copy the filter string to another table with the same source the table which i put the filter string shows up with the columns filters block and i can't use them. how do i unblock after i put an filter string?

**Comment by davidegironi** [comment]
Hello, I'm sorry but I don't understand what you mean.
Can you please build up a sample project?

**Comment by pereiragtiago** [comment]
> Hello, I'm sorry but I don't understand what you mean. Can you please build up a sample project?

so in my situation when filter or sort a table i save the sort and the filter string in two separated strings for another table with the same data source from another form. when i load the table from another form insert the same data source, but i apply the filter and sort from the strings that save previous, but when i do this the columns filters of table from another table stay block, i cant use them or ever clear the sort. i want to be able to put the tables with same data source, from others forms to share the same filter and sort string, but columns filters and sort need to be editable for the users, not blocked.

**Comment by davidegironi** [comment]
Now I get it. It is how the filter/string save and restore mechanism works. That is because it save's the filter and sort string, not the filter and sort component state. Doing that kind of froze will be fairly difficult. It has been discussed before here in the issues list. Unluckily I've no time to spend on this development at present. But if you want to contribute with this feature It will be a pleasure to review it and possibly merge it.
