### ISSUE TITLE
bitmap columns

### ISSUE THREAD

**Issue by aa4re** [davidegironi/advanceddatagridview#25]
Hello, I thank you very much for your magnificent work. Today I have tried to use the Advanced DataGridView control but the filter and sorting of bitmap type columns does not work. I use the column of type bitmap to list the complete and pending tasks, it will be very interesting to add a functionality to sort and list this type of columns basing for example on its index.
Forgive for my language I do not speak English.
Thank you

**Comment by davidegironi** [comment]
Hello @aa4re, thank you for your suggestion, it will be really a nice feature! There are a few points you need to change in order to add the typeof(Bitmap) Sort and Order methods, most of them in ColumnHeaderCell.cs class. If you are going to implement this please share with us. I will implement this maybe in the next version, as soon as I have time to work on this.
