### ISSUE TITLE
New feature request: SetFilterCustomVisibility

### ISSUE THREAD

**Issue by tumbelo** [davidegironi/advanceddatagridview#38]
"SetFilterCustomVisibility" would be great feature. I mean: I will never let user use custom filters, so user may be confused if custom filters are visible (even grayed as inactive with SetFilterCustomEnabled). Would be clearer, if there wouldn't be custom filter menu items visible at all.

**Comment by davidegironi** [comment]
@tumbelo , thank you for the suggestion. It takes a bit to trim the resizing function in order to work with a custom/visibility behaviour. As soon as I have time I'll try to code this. For the next release, the thing I could do, is to Disable even the "Custom Filter" ToolStripMenuItem, that way it would be clear if it's enable.
