### ISSUE TITLE
Port to .NET 5

### ISSUE THREAD

**Issue by billpeet** [davidegironi/advanceddatagridview#49]
The future of .NET is .NET 5 :)
It appears the DG.AdvancedDataGridView NuGet package actually works on a .NET 5 project (even if NuGet complains), it looks like it's at least partly compatible.
Any chance of officially targeting .NET 5 in a future release?

**Comment by davidegironi** [comment]
Hello @billpeet ,
unluckily I've no plan for .NET 5 or .NET Core, time to develop this open project is reduced. Also, up to now NET.5 is still RC, i think I will in the future skip .NET Core and go to .NET 5, when it will be stable. Of course hope I've time to perform this task.

**Comment by kirsan31** [comment]
@davidegironi if your still interested, I made it [here](https://github.com/kirsan31/advanceddatagridview/tree/156b0ba5218de0aeccfe7e796606616938d34904). And it's working.

What done:
- SDK projects format.
- Multitargeting with `net5.0-windows` and `net40`.

What was not checked:
- `_DevTools` dir.
- NuGet stuff.

**Comment by davidegironi** [comment]
I'm working on the net5 version. I think I will make a new branch. NET5 works, but I want to write the compiling script for dll and nuget package. I'm almost done with both, I think next week I'll have time to work on this.

**Comment by davidegironi** [comment]
Hello, check this out: https://www.file.io/download/lRRkuJowXmFN
Target net40 and net5.0-windows.
Updated the AutoBuild script and the NuGet builder, now both works (find AutoBuild updated version here: http://davidegironi.blogspot.com/2014/04/autobuild-is-build-automation-tool-for.html)
I've done my porting from nonSDK to SDK project, cause in your one there are a few things changed in the sln file also.
Check it out and let me know. Once you have done I'll post this no nuget, then I'll add the other changes requested here: https://github.com/davidegironi/advanceddatagridview/issues/60

**Comment by kirsan31** [comment]
Hi @davidegironi. Sorry I have very hard time at work for now. I will back as soon as I can.

**Comment by davidegironi** [comment]
As a side note, if you want to check also the menustrip mod, you can find it here: https://github.com/davidegironi/advanceddatagridview/issues/58#issuecomment-819727960

This update contains the rewrite of the checklist filter logic, it's quite important. So It's better to check it a lot before publishing.

**Comment by kirsan31** [comment]
@davidegironi

> Hello, check this out: https://www.file.io/download/lRRkuJowXmFN

Hi, I looked at the code, and use .net5 version for some time and all seems ok (in terms of porting to .net5).


> As a side note, if you want to check also the menustrip mod, you can find it here: #58 (comment)

File is not available any more.

P.s. While testing, I found some not serious memory problems in demo app and in lib too. But fixes are trivial. More serious problem is memory leak in ColumnHeaderCell :(
In [OnColumnAdded](https://github.com/davidegironi/advanceddatagridview/blob/f6fdac4e9e933dffa227e7cfdaeb2001ccb5e64b/AdvancedDataGridView/AdvancedDataGridView.cs#L975) we replace existing `HeaderCell` with our `ColumnHeaderCell`. So, in [ColumnHeaderCell constructor](https://github.com/davidegironi/advanceddatagridview/blob/f6fdac4e9e933dffa227e7cfdaeb2001ccb5e64b/AdvancedDataGridView/ColumnHeaderCell.cs#L53) we need to do a full clone of existing `HeaderCell` to dispose it after cloning. But this doesn't happens. Same in [Clone](https://github.com/davidegironi/advanceddatagridview/blob/f6fdac4e9e933dffa227e7cfdaeb2001ccb5e64b/AdvancedDataGridView/ColumnHeaderCell.cs#L107) method.
With current implementation we simple reference elements of old `HeaderCell` and this lead to impossibility of GC it.

In constructor we need to clone base `DataGridViewColumnHeaderCell` and if `HeaderCell` is `ColumnHeaderCell` clone new elements too (including `MenuStrip`).
This is not very trivial task and not possible without reflection (needed for cloning event handlers) :(

I'll be back as soon as I can (still troubles at work), hopefully in a few days.

**Comment by davidegironi** [comment]
Thank you @kirsan31 .

You can find the file here: https://file.re/2021/04/19/advanceddatagridview/

About the Memory Leak, I've built after this issue https://github.com/davidegironi/advanceddatagridview/issues/41 the "Memory  Test" button.
I've checked it with net40, no problem at all. The behaviour under net5.0 indeed is different. This is a bit wired.
I thought
https://github.com/davidegironi/advanceddatagridview/blob/f6fdac4e9e933dffa227e7cfdaeb2001ccb5e64b/AdvancedDataGridView/AdvancedDataGridView.cs#L994
should fix the problem but it's not like this.
I have to investigate on this. If you find a solution please share it with me, using the last code I send you. Thanks!

**Comment by kirsan31** [comment]
@davidegironi Sorry, I haven't checked [this](https://file.re/2021/04/19/advanceddatagridview/) yet :( Still have very little free time.
Demo app is leaking itself, net40 after 1 memory test: 
![image](https://user-images.githubusercontent.com/17767561/115892853-3ea8d600-a460-11eb-978f-e43d4d78f6d1.png)
I have fixed it [here](https://github.com/kirsan31/advanceddatagridview/commit/c19dcb2336755c2e7f72e4d629f4a68e4902077d) (with some small additional improvements). 
Also some [small memory fixes](https://github.com/kirsan31/advanceddatagridview/commit/f6d2f81b0881009cf5fe31f5781b961667c84964).

About huge memory leak on .Net5. The main problem of it I described in previous post. Now why on net4 we have only small leak and on .Net5 huge.  This workaround:
https://github.com/davidegironi/advanceddatagridview/blob/f6fdac4e9e933dffa227e7cfdaeb2001ccb5e64b/AdvancedDataGridView/AdvancedDataGridView.cs#L190-L206
Not working on .Net5 because `Columns` already empty here. They are cleared [here](https://github.com/davidegironi/advanceddatagridview/blob/f6fdac4e9e933dffa227e7cfdaeb2001ccb5e64b/AdvancedDataGridViewSample/FormMain.Designer.cs#L18), with disposing of [bindingSource_main](https://github.com/davidegironi/advanceddatagridview/blob/f6fdac4e9e933dffa227e7cfdaeb2001ccb5e64b/AdvancedDataGridViewSample/FormMain.Designer.cs#L55).

We need properly dispose `ColumnHeaderCell` in `OnColumnRemoved` as your originally [discuss](https://github.com/davidegironi/advanceddatagridview/issues/41#issuecomment-645949832). But the [main problem](https://github.com/davidegironi/advanceddatagridview/issues/49#issuecomment-822561513) prevent doing it. I will think of some  workaround, because doing it right a bit challenging :)
Will be back as soon as I can.

**Comment by davidegironi** [comment]
Hello @kirsan31 
Thank you for your job,
I wasn't that much interested in the sample project FormMain investingation, but as you pointed out it turns out it has big memory leak.
In a few days I'll publish an update containing

- net40 and net5.0 update
- SDK solution format
- leak fixed
- MenuStrip new logic, with max checklist nodes enabler

It will be a major number update.
Up to my test all works. Here is the version I'll publish, If you want to check it out: https://file.io/NI8xeXxT2RVg
Next version will come out in a few weeks. I'll add the fix you suggested here: https://github.com/davidegironi/advanceddatagridview/issues/60
