### ISSUE TITLE
Custom Filter textbox interferes with dropdown

### ISSUE THREAD

**Issue by ShammyLevva** [davidegironi/advanceddatagridview#77]
![image](https://user-images.githubusercontent.com/29687786/147857999-26668ffe-236e-496f-b7b7-1aa91c57fcdb.png)

Thanks for the great control. As you can make out on the screenshot the textbox is interfering with the dropdown control. This may be something to do with DPI scaling, or it may just need the text control forced to anchor to the dropdown rather than anchor to the window.

**Comment by ShammyLevva** [comment]
Whilst I've raised an issue a question - is it possible to set a setting to disable the custom filter option?

**Comment by davidegironi** [comment]
Hello @ShammyLevva,
thank you for your feedback.
You can use **DisableFilterCustom** method to disable the custom filter.
It can also be due to the **Scale and Layout** settings of windows.
Unluckily I'm not able to reproduce this error cause I'ven't got an high resolution monitor, so I can check and fix it. If you find a fix please share this. The lines that shows this control are here https://github.com/davidegironi/advanceddatagridview/blob/ca7cfeaaaf40e666db2175de3954de3cc041edfa/AdvancedDataGridView/FormCustomFilter.cs#L160

Let me know

**Comment by ShammyLevva** [comment]
Thanks I will have a play around whilst I'm on holiday at start of New Year. It may just be a call to the windows system to set DPI awareness is what is needed so the control is responsive to users display settings.

**Comment by davidegironi** [comment]
Let's keep me updated. Thank you.
